jupyterlite/cockle

LICENSE, package.json
Follow-up to the move to the `jupyterlite` organization.
=> Rename package to `@jupyterlite/cockle`

.github/workflows/check-release.yml, .github/workflows/enforce-labels.yml, .github/workflows/prep-release.yml, .github/workflows/publish-release.yml, .gitignore, CHANGELOG.md, README.md, RELEASE.md, package.json, tsconfig.json
To streamline the release of the package to `npm`, using the same process as other packages in the `jupyterlite` organization.
=> Add releaser workflows

src/commands/ls.ts, tests/commands/ls.test.ts
Fix `ls` of empty directory returning nothing rather than showing an obscure `map` error.
=> Fix empty listing

src/commands/builtin_command_runner.ts, src/commands/wasm_command_runner.ts, src/context.ts, src/environment.ts, src/shell.ts, src/wasm/grep.js, tests/commands/cd.test.ts, tests/commands/env.test.ts
This PR adds a new `Environment` class that is a collection of environment variables that are owned by the `Shell`. These are copied into an individual WASM command's environment before the command is run, and changes are copied back out again afterwards. The copying in occurs in the `preRun` callback of the WASM module's constructor, which is a better place for the file system setting up so that is moved there as well.
Persistent environment variables are also required for builtin commands. A good example (the only builtin command so far) is `cd` which stores the current working directory in the `PWD` envvar and this is explicitly tested in a new test.
=> Support environment variables that persist beyond single commands

src/commands/builtin_command_runner.ts, tests/commands/cd.test.ts
Support `cd -` which cd's into the previous directory. Uses `OLDPWD` environment variable. Also checks number of argument passed to `cd` command and throws error if there are more than one. `cd` on its own without any arguments is not an error.
=> Support 'cd -'

src/commands/wasm_command_runner.ts
For WASM modules containing commands, we currently use the properties `callMain`, `ENV`, `FS` and `getEnvStrings`. `callMain` is always required as otherwise we can't call the command, but the others are optional and are only required for commands that access the filesystem (`FS`) or get/set environment variables (`ENV`, `getEnvStrings`). The PR checks for the existence of these properties before using them, throws an error if `callMain` is missing but otherwise continues if any of the others are missing.
=> Check WASM module properties exist before using

src/commands/builtin_command_runner.ts, src/commands/coreutils_command_runner.ts, src/context.ts, src/io/buffered_output.ts, src/io/console_output.ts, src/io/file_input.ts, src/io/file_output.ts, src/io/input.ts, src/io/output.ts, src/io/pipe.ts, src/io/redirect_output.ts, src/io/single_char_input.ts, src/io/terminal_input.ts, src/shell.ts, tests/shell.test.ts
This PR implements pipes. For example, running in JupyterLite terminal extension:
It includes a slight refactor of the input and output classes, and some tidying of `names` of the `CoreutilsCommandRunner`.
=> Implement pipes

src/commands/builtin_command_runner.ts, src/context.ts, src/history.ts, src/shell.ts, tests/history.test.ts
This adds storage of command history with the following functionality:
- `history` command
- Use of `!` followed by number to rerun a command from the history
- Scrolling up and down in the history using up and down arrows
=> Add storage of command history

package-lock.json, package.json, src/commands/coreutils_command_runner.ts, src/commands/wasm_command_runner.ts, src/environment.ts, src/shell.ts, src/wasm/coreutils.js, src/wasm/grep.js, tests/commands/ls.test.ts, tests/commands/stty.test.ts, tests/commands/tty.test.ts, tests/shell.test.ts
This PR adds support for correct terminal handling of number of columns, set using `Shell.setSize`. An example of a command that uses this is `ls`, which by default writes the file and directory list in a number of columns that fit in the terminal width.
The terminal size is stored as environment variables `LINES` and `COLUMNS`. These can be checked using the commands `env` or `stty size`.
In terms of implementation, if `stdin` is not specified when loading the JS/WASM command file then stdin is a valid TTY. To get this to work as we desire two functions are monkey-patched, one which returns the window size (otherwise hard-coded as 24x80) and the other is the `get_char` function by which we pass in stdin characters one at a time.
I have modified both `coreutils.js` and `grep.js` to export …
=> Support terminal handling of columns

package-lock.json, src/history.ts, src/shell.ts, tests/history.test.ts
Added more to shell history:
1. Programmatically set `maxSize` (will probably be env var eventually).
2. Ignore duplicate commands.
3. Ignore commands with leading whitespace.
And more comprehensive testing.
=> History maxSize and ignore duplicates and leading whitespace

src/aliases.ts, src/commands/builtin_command_runner.ts, src/commands/coreutils_command_runner.ts, src/context.ts, src/environment.ts, src/index.ts, src/parse.ts, src/shell.ts, src/tokenize.ts, tests/aliases.test.ts, tests/commands/alias.test.ts, tests/commands/cd.test.ts, tests/commands/env.test.ts, tests/parse.test.ts, tests/shell.test.ts, tests/tokenize.test.ts
Add initial support for aliases. It is not yet possible to set a new alias from a `Shell` as this will require parsing of quote-delimited strings, but there are hard-coded aliases in the `Aliases` constructor. The primary motivation here is to set some default use of colour in various commands for the upcoming coloured output PR.
The aliases work when running commands and for tab completion, and the `alias` command writes the current aliases to stdout.
=> Add support for aliases

src/commands/coreutils_command_runner.ts, src/environment.ts, src/io/file_output.ts, tests/shell.test.ts, tests/shell_setup.ts
Support coloured output for `ls` and `grep` commands. This is actually a surprisingly small change in the code just to set the `TERM` environment variable, now that aliases are set up to use colour in both `ls` and `grep` commands by default. It uses the default `ls` colours which can be checked using `dircolors --print-ls-colors`; these could be overridden by setting an `LS_COLORS` env var.
=> Support coloured output for ls and grep commands

package-lock.json, src/tokenize.ts, tests/commands/env.test.ts, tests/parse.test.ts, tests/shell.test.ts, tests/tokenize.test.ts
Add support for single and double quotes in the command line, so commands like
```bash
lua -e "A=3; B=7" -v
```
or the same with single quotes.
There is no support yet for backslashed quotes `\"`, or indeed any form of backslashed characters.
=> Support quotes in command line

src/parse.ts, src/shell.ts, src/tokenize.ts, src/utils.ts, tests/parse.test.ts, tests/shell.test.ts, tests/tokenize.test.ts
We already had some tab completion of commands and aliases, this improves the situation with:
1. Parses the string from the command line to correctly identify if we are trying to complete a command or not, such as when following a pipe, etc.
2. Prints the possible matches in columns.
3. Prints all of the commands and aliases if you tab complete an empty string.
4. If all of the possible matches start with the same text that is longer than the entered command, updates the entered command to this start text.
Still need to add tab completion of filenames.
=> Improvements to command/alias tab completion

src/commands/builtin_command_runner.ts, src/commands/wasm_command_runner.ts, src/context.ts, src/io/terminal_output.ts, src/shell.ts
Use a separate `TerminalOutput` for stderr, and add the colour ANSI escape codes automatically.
=> Use separate TerminalOutput for stderr

src/builtin/export_command.ts, src/builtin/index.ts, src/command_registry.ts, test/tests/command/export.test.ts, test/tests/command_registry.test.ts, test/tests/shell.test.ts
Add `export` as a new built-in (TypeScript) command, so that it is possible to export new environment variables to the environment that is shared between all commands.
For example:
```bash
export SOME_NAME='some value'
```
=> Add export command

src/ansi.ts, src/environment.ts, src/shell.ts
Fixes #18.
This moves all ANSI escape sequences into their own module `ansi.ts` and gives them sensible names. Although the original plan was to use an external module for this, only a few codes are needed at this stage so this will suffice.
=> Separate module for ANSI escape sequences

src/ansi.ts, src/shell.ts, test/tests/shell.test.ts
This adds support for editing within the input command line:
1. Left and right arrows to move cursor one character at a time.
2. Insert new character at cursor position rather that always at the end.
3. Delete at cursor position to accompany backspace which is already implemented.
4. Home and End to move cursor to start and end of command line.
5. Shift/alt left and right arrows to move back and forward a word (separated by whitespace) at a time.
6. Tab completion at the cursor location whilst keeping the remainder of the command line.
I have been a bit permissive about what keystrokes correspond to these, to ensure that this works on both of my test machines (linux and macos). In time we may need to tighten this up and make some OS-specific. This will need multi-platform testing, both …
=> Support command-line editing

src/ansi.ts, src/builtin/clear_command.ts, src/builtin/index.ts, src/io/buffered_output.ts, src/io/console_output.ts, src/io/output.ts, src/io/terminal_output.ts
Add `clear` built-in command. Does nothing if `stdout` does not support ANSI escape codes, i.e. is not a terminal.
=> Add clear built-in command

.github/workflows/check-release.yml
So it uses a name related to this repo, which is less confusing when downloading and extracting the artifact locally.
=> Update releaser artifact name

src/command_registry.ts, src/commands/coreutils_command_runner.ts, src/commands/grep_command_runner.ts, src/commands/wasm_command_runner.ts, src/defs.ts, src/shell.ts, src/shell_impl.ts, src/shell_worker.ts, src/wasm_loader.ts, test/package.json, test/serve/index.ts, test/serve/shell_setup.ts
Up until now we have been importing the JavaScript-with-embedded-WebAssembly modules statically at build time just like any other TypeScript/JavaScript code. This PR changes this to dynamically import such code on demand using the WebWorker `importScripts` function. There are two benefits:
1. It will support (with a little more work) separate JS and WASM files. This will be in a follow-up PR.
2. It will be possible (with a larger amount of more work) to register the WASM commands available at runtime, probably when constructing a `Shell` object, to support arbitrary terminal functionality written by ourselves or any user.
To dynamically import such modules they have to be available at some URL. At this stage I have implemented a really simple solution to this in the test suite and …
=> Load WASM/JS modules dynamically using importScripts

demo/package.json, package.json, src/commands/wasm_command_runner.ts, src/error_exit_code.ts, src/shell_impl.ts, test/package.json, test/playwright.config.ts, test/rspack.config.js, test/serve/shell_setup.ts
With the merging of emscripten-forge/recipes#1278 there are now the following packages on Emscripten-forge with separate JS and WASM files:
- `cockle_fs` build 2
- `coreutils` build 4
- `grep` build 4
This PR uses these new WASM files, most of the changes for this are trivial as the work has already been done and `importScripts` automagically works for the `.wasm` files provided they are served from the same directory as the `.js` files.
The other changes are to deal with not having to call `callMain` anymore, the calls happens automatically when a JS/WASM `Module` is instantiated.
I have changed the playwright test settings to run a single test at a time as without it there were some problems with multiple tests trying to load JS/WASM files at the same time. It is probably just my …
=> Support separate WASM/JS files and remove use of callMain

.github/workflows/publish-release.yml
Micromamba is needed in release actions to perform the `fetch:wasm` step.
=> Pre-install micromamba in release actions

demo/package.json, package.json, test/package.json
The just-released version 0.0.6 of cockle doesn't package the WASM files correctly, which is fixed by this PR. When packaging, WASM files are included only in the `lib` not `src` directory as we do not want to ship two copies of each of these potentially large files. This will affect downstream libraries as they will need to extract the WASM files from `lib` not `src`.
=> Fix packaging of wasm files

src/shell_worker.ts, test/serve/index.ts, test/serve/input_setup.ts, test/tests/shell.test.ts
Support repeat use of `BufferedStdin`, fixes #48. The fix itself is quite simple, we weren't fully clearing the buffered stdin on the web worker side by calling `_clear()`.
Also included here is the testing framework to test use of buffered terminal stdin whilst a command is running. This runs two `async` tasks concurrently, the first is the command to run and the second is the terminal stdin to provide whilst the command is running. The latter starts with a short delay so that the command is actually running, otherwise the terminal stdin is just appended to the end of the command input string.
=> Support repeat use of BufferedStdin

src/builtin/cd_command.ts, src/io/terminal_output.ts, src/shell_impl.ts
Standardise linefeed/newline handling. On input from `xterm` we receive a carriage return `\r` to submit a command, but the options passed to `xterm` by JupyterLab require `\r\n` to both move to the next line and to the start of the line. Internally within cockle we emit a `\n` for a newline and `ShellImpl.output`, which calls the `outputCallback` passed in by the frontend, converts this to the required `\r\n`. Before this PR the conversion happened in `TerminalOutput` and in a number of other places for specific returns. It is better to keep it in just one place as is done here.
=> Standardise linefeed/newline handling

src/commands/wasm_command_runner.ts, src/io/input.ts, src/io/input_all.ts, src/io/terminal_input.ts, test/tests/shell.test.ts
Whilst running a command that accepts stdin, such as `wc` or `cat` without any arguments, stdin should be echoed back to stdout a character at a time. This PR does this in the `getChar()` that is monkey-patched into the command's WASM wrapper. It only does so if stdout is the terminal, if it is a file for example then it is not echoed. Perhaps the code should alternatively go in `TerminalInput`, but then that would need access to the current `TerminalOutput` too.
It is not fully correct for the situation of `cat` accepting multiple lines of input, as here all the output is written at once at the end of the command. What should actually happen is that the command should write each line after it receives a carriage return. I think this occurs because the WASM commands are not set up to …
=> Echo buffered stdin (whilst running a command) back to stdout

src/commands/wasm_command_runner.ts, test/tests/command/touch.test.ts
Temporary workaround for issue #17 that filters out the error. The exit code is still incorrect. This will be fixed properly at a later date.
=> Ignore touch bad file descriptor, but still have incorrect exit code

package-lock.json, package.json
Remove `@jupyterlab/services` as a dependency. It hasn't been needed since we switched from using `Contents.IManager` to `DriveFS` for the filesystem integration with JupyterLite.
=> Remove @jupyterlab/services as a dependency

package-lock.json, package.json, src/commands/wasm_command_runner.ts, src/defs.ts, src/shell_impl.ts, src/wasm_loader.ts, worker.rspack.config.js
These are changes required to ensure the latest code here works in the JupyterLite terminal. Changes are:
1. Override WASM `locateFile` to load WASM files from the same directory as their JS wrapper files.
2. Prebuilding the WebWorker bundle using `rspack` (`webpack` would also work).
Whilst doing item 1 I have also chosen to make the `wasmBaseUrl` option compulsory, as all existing uses set it anyway.
Item 2 is a temporary fix so that the WebWorker works OK in a JupyterLite deployment. It should, and eventually will, be in the terminal extension instead.
After this is merged I will release version 0.0.8 and make the corresponding changes in the terminal extension.
=> Prebuild worker bundle and import WASM files from same directory as JS wrappers

src/commands/wasm_command_runner.ts, src/environment.ts, test/tests/shell.test.ts
When outputting commands that are colored, such as `grep`, to file, no color should be used. This is achieved here by not setting the `TERM` environment variable for the command.
Behaviour before this PR:
and after:
=> Prevent use of color in command output to file

.gitignore, package.json, src/builtin/cockle_config_command.ts, src/builtin/index.ts
Add a new `cockle-config` command that shows the cockle version being run. Eventually this will also include information about the commands available.
=> Add new cockle-config command that prints cockle version

package-lock.json, package.json, src/tools/prepare_wasm.ts
This adds validation of the cockle config JSON files introduced in #61. Schema validation uses [zod](https://github.com/colinhacks/zod) as it is small, and the validation occurs in the `postbuild` stage (i.e. `jupyter lite build`) rather than at runtime so there is no detrimental impact on speed or download size when a `Shell` is started.
=> Validate JSON config files

src/shell_impl.ts, test/serve/index.ts, test/serve/shell_setup.ts, test/tests/shell.test.ts, test/tests/utils.ts
Add support for simple filename expansion of arguments to commands using `*` and `?`.
=> Support filename expansion of * and ?

src/defs.ts, src/defs_internal.ts, src/shell.ts, src/shell_impl.ts, src/shell_worker.ts
The definitions of interfaces and options are combined in `defs.ts` for both external classes (`Shell`) and internal (`ShellWorker`, `ShellImpl`) ones. Here splitting them so that the external ones stay in `defs.ts` and the internal ones are in `defs_internal.ts`, so that client projects such as `terminal` can ignore the internal ones.
=> Separate external and internal defs

demo/serve/demo.ts
Use xtermjs `onData` rather than `onKey` for the demo as that is what is used in JupyterLab:
https://github.com/jupyterlab/jupyterlab/blob/48908a8b07128b651faab72434f8d442b99bc91c/packages/terminal/src/widget.ts#L366
This supports better mapping of keys to characters, and also pasting into the terminal.
=> Use xtermjs onData rather than onKey

CHANGELOG.md, src/tools/prepare_wasm.ts
Add new environment variable `COCKLE_WASM_EXTRA_CHANNEL` used when building a deployment to look in an extra Emscripten-forge channel, remotely or locally, as well as the default channels. This is useful when trying to build new wasm commands in a local Emscripten-forge `recipes` repo.
For example, if I have my local Emscripten-forge recipes repo in `~/github/emscripten-forge/recipes` then to build the `demo` here I could use:
```bash
COCKLE_WASM_EXTRA_CHANNEL=~/github/emscripten-forge/recipes/output npm run build
```
and the `cockle-command` output when served is:
=> Add COCKLE_WASM_EXTRA_CHANNEL env var to get wasm command packages from an extra channel

src/commands/wasm_command_runner.ts, test/tests/shell.test.ts
When a wasm command is running, stdin can take a multi-character string such as an ansi escape sequence. This PR supports such multi-character inputs by passing on all the characters one at a time rather then just the first character.
=> Support multi-character inputs (escape sequences) whilst command running

test/serve/output_setup.ts, test/tests/command/ls.test.ts, test/tests/command/stty.test.ts, test/tests/command/touch.test.ts, test/tests/history.test.ts, test/tests/shell.test.ts, test/tests/utils.ts
Add new function `MockTerminalOutput.textAndClear` that combines `text` and `clear` to simplify some tests.
=> Add MockTerminalOutput.textAndClear function

src/builtin/exit_command.ts, src/context.ts, src/shell_impl.ts
`IOutput.write` and `flush` were converted from async to sync in #77 but I missed a few `flush` calls, which are corrected here.
=> Remove some missed async flush calls

src/buffered_io.ts, src/commands/wasm_command_runner.ts, test/tests/shell.test.ts
Move `stdin` echoing from the `getChar` callback to `BufferedIO` so that it can use the correct `termios` settings.
=> Move stdin echoing to BufferedIO

src/tools/prepare_wasm.ts
When specifying a local wasm command package in `cockle-config-in.json`, if it starts with a `~` then replace it with the value of the `HOME` environment variable.
=> Convert ~ to HOME in local package config

src/callback.ts, src/io/terminal_output.ts, test/serve/output_setup.ts
Make external `IOutputCallback` synchronous as it does not need to be async, the same as in JupyterLab. This is an API change, so will need a corresponding change in the JupyterLite Terminal when this is released.
=> Make external IOutputCallback synchronous

demo/serve/demo.ts, src/buffered_io.ts, src/history.ts
Fixes #89.
Fixes a bug when writing to `stdout` sometimes blocks so the shell freezes. This was due to not handling all of the possible returns from `Atomics.waitAsync` as sometimes the wait is resolved immediately and the new value returned rather than a `Promise`.
This will be following by a new release (0.0.13) as it is a significant bug.
=> Fix blocking writes by correctly handling Atomics.waitAsync returns

src/builtin/cockle_config_command.ts, src/command_registry.ts, src/commands/wasm_command_module.ts, src/commands/wasm_command_runner.ts, src/context.ts, src/shell_impl.ts, src/wasm_module_cache.ts, src/wasm_module_loader.ts
Display wasm module cache status in `cockle-config`, as shown in the second table here:
Eventually we will add more control here to allow clearing of the cache, preloading of wasm modules, etc.
I have also renamed `WasmLoader` to `WasmModuleLoader`, and there is a new class `WasmModuleCache` rather than it being part of the loader.
=> Display wasm module cache status in cockle-config

src/tools/prepare_wasm.ts
Add `emscripten-forge-dev` channel as the first choice to obtain Emscripten-forge packages from, to support emscripten 3.1.73. Now that such packages depend on a particular `emscripten-abi` version, they will not be used unless all the required packages are compiled with emsdk 3.1.73.
=> Add emscripten-forge-dev channel

src/builtin/cockle_config_command.ts, src/commands/wasm_command_module.ts, src/commands/wasm_command_runner.ts, src/shell_impl.ts, src/tools/prepare_wasm.ts, src/wasm_module_cache.ts, src/wasm_module_loader.ts
Wasm command files are currently all put in the same directory for static serving. There can be multiple modules (i.e. `.wasm` files) per emscripten-forge package, and although the package names are unique there may be multiple modules with the same name in different packages. So to avoid future name conflicts, here I am changing the directory structure for the static serving so that each package is in its own directory.
Summary of changes:
1) Wasm module loading expects `wasmBaseUrl/package/module.js` (and `.wasm` etc) rather than just `wasmBaseUrl/module.js`.
2) `prepare_wasm.ts` puts modules in these package directories.
This will need a corresponding change in JupyterLite terminal `add_on.py` to use the package directories when this is next released.
=> Use separate directories for wasm command packages

cockle-config-base.json, demo/cockle-config-in.json, package-lock.json, package.json, src/shell_impl.ts, src/tools/prepare_wasm.ts, test/cockle-config-in.json
Improve config JSON file format. Rather than use arrays of dicts, this uses dicts that map from package or module name to their properties. It makes them more complex to parse, but the config files themselves are more concise and will allow us to add other configuration options such as aliases and env vars. A key benefit now is that you can use a config JSON file to override the base one (`cockle-config-base.json`) if you want to test a different local build of a core package, or which commands that `coreutils` exposes, etc.
=> Improve config JSON file format

src/tools/prepare_wasm.ts
Now that `emscripten-forge-dev` channel is working well, with packages compiled using emscripten 3.1.73, we can remove the `emscripten-forge` channel for packages compiled using 3.1.45 and/or 3.1.58. Although it is possible to mix packages compiled using different emscripten versions (I've tested 3.1.58 and 3.1.73 together) in general this will not be the case, and in fact the emscripten ABI pins should enforce a single emscripten version when resolving emscripten-forge packages in `prepare_wasm.ts`. It is still possible to try out packages using a different emscripten version via the `local_directory` option in `cockle-config-in.json`.
=> Remove use of default emscripten-forge channel

src/ansi.ts, src/callback.ts, src/defs_internal.ts, src/download_tracker.ts, src/shell.ts, src/shell_impl.ts, src/shell_worker.ts, src/wasm_module_loader.ts
This provides visual feedback in the form of an animated message in the terminal when downloading wasm modules if they are taking a long time (> 0.3 seconds). Here is an example of it in action:
https://github.com/user-attachments/assets/b6971f25-5995-4128-ae04-355feea8f79b
The form of the feedback is hard coded in the `DownloadTracker` class. Eventually I expect this will be configurable and optional, and perhaps could be extended with signals so that the feedback could be displayed elsewhere in JupyterLite as discussed elsewhere for kernels downloading packages.
=> Provide visual feedback when downloading wasm modules

package-lock.json, package.json
`deepmerge-ts` needs to be in `dependencies` not `devDependencies` at it is used in `prepare_wasm.ts` by downstream projects such as `terminal` and `cockle-playground`.
=> Add deepmerge-ts to dependencies

.github/workflows/check-release.yml, .github/workflows/prep-release.yml, .github/workflows/publish-release.yml, .github/workflows/test.yml, package-lock.json, package.json, src/cockle_drive_fs.ts, src/shell_impl.ts
Switch the JupyterLite `DriveFS` access to use the service worker as is done in both pyodide and xeus kernels in situations with a similar architecture (kernel/terminal running in a webworker, communicating with main worker using `comlink`, `DriveFS` accessed from webworker).
Fixes #106. Tested locally to show this. We will need a new release after this followed by testing and release of `terminal`.
=> Use service worker based DriveFS

demo/playwright.config.ts, package-lock.json, package.json, src/shell.ts, src/shell_worker.ts, test/playwright.config.ts, test/serve/shell_setup.ts
Use a `ready` `PromiseDelegate` (from `@lumino/coreutils`) to indicate when a `Shell` is ready to be started. This ensures that the shell is not used until the web worker is fully ready to do so, and allows us to resume running tests in parallel without any `sleep` calls. Have returned `workers` setting in `playwright.config.ts` to its default.
FIxes #50.
=> Use ready promise before starting shell

src/commands/command_module_loader.ts
If `importScripts` fails then currently the download feedback notification continues for ever. This ensures it stops.
=> Stop download notification if fail to importScripts

.prettierignore, src/commands/command_module_cache.ts, src/commands/command_module_loader.ts, src/commands/wasm_command_runner.ts, src/error_exit_code.ts, src/file_system.ts, src/fs.d.ts, src/shell_impl.ts
Use TypeScript type definitions for WebAssembly modules. These are generated at compile time in the emscripten-forge recipe for `cockle_fs` so that they use the same version of emscripten as the WebAssembly commands, rather than the `npmjs` package `@types/emscripten`.
This allows us to reduce the number of `any` types for interacting with WebAssembly modules.
=> Use TypeScript type definitions for WebAssembly modules

src/builtin/alias_command.ts, src/builtin/cd_command.ts, src/builtin/export_command.ts, src/builtin/history_command.ts, src/builtin/options.ts
Simplify syntax of `Options` argument parsing, removing the complex generic syntax in `fromArgs`.
=> Simplify syntax of Options argument parsing

src/tools/prepare_wasm.ts
Support the use of emscripten WebAssembly debug builds that include source map files with names like `moduleName.wasm.map`, as obtained using the compilation flags `-g -gsource-map`.
Also removed checking for filesystem-only module files as not currently using any of these.
=> Support WebAssembly source map files

test/serve/shell_setup.ts, test/tests/command/vim.test.ts, test/tests/shell.test.ts
Set an initial size for terminal in tests of 24 rows and 80 columns rather than leaving the size unspecified. Also enabling color in `vim` tests as without this the `TERM` environment variable is not set.
=> Set an initial size for terminal in tests

test/serve/index.ts, test/serve/keys.ts, test/tests/command/nano.test.ts, test/tests/command/vim.test.ts, test/tests/history.test.ts, test/tests/shell.test.ts, test/tests/termios.test.ts
Add a `keys` object that is available in in-browser tests to avoid redefining them in multiple tests.
=> Reuse common key definitions in in-browser tests

src/buffered_io.ts, src/commands/wasm_command_runner.ts
Remove extraneous newline when closing `vim` or `nano`. Fixes #157.
Here resetting the current write column to zero when setting `termios`.
=> Remove extraneous newline when closing vim or nano

src/buffered_io.ts, src/callback.ts, src/io/input.ts, src/io/input_all.ts, src/io/terminal_input.ts
Support returning all buffered characters in stdin `read` function. This isn't need by WebAssembly commands as they always specify an integer max characters that they can accept, but it will be useful for JavaScript commands so that they can read, for example, a whole escape sequence from the keyboard in one call.
=> Support returning all buffered characters in stdin read function

package.json
Add `sideEffects` config to `package.json` to specify that none of the `cockle` code contains side effects such as statically running code when JavaScript files are imported. This setting is used by bundlers such as `webpack` to support tree shaking, i.e. removal of `cockle` dead code when building downstream projects that use `cockle`. This will be important when building JavaScript commands for `cockle` that contain some but not all (of course) of the `cockle` code.
=> Add sideEffects config to package.json

.gitignore, demo/cockle-config-in.json, test/cockle-config-in.json, test/util-js/README.md, test/util-js/js-capitalise.js, test/util-js/js-test.js, test/util-js/lib/js-capitalise.js, test/util-js/lib/js-test.js, test/util-js/package-lock.json, test/util-js/package.json, test/util-js/rollup.config.js, test/util-js/src/js-capitalise.ts, test/util-js/src/js-test.ts, test/util-js/tsconfig.json
Build JavaScript commands for testing from TypeScript source using `rollup`. This ensures the types are correct, and acts a an example of how to build such JavaScript commands for use in `cockle`.
Using `rollup` as the configuration is fairly simple and the generated JavaScript bundles are easy to understand.
TypeScript source for `js-test.ts`:
```ts
import type { IJavaScriptContext } from '@jupyterlite/cockle';
import { ExitCode } from '@jupyterlite/cockle';
export async function run(cmdName: string, context: IJavaScriptContext): Promise<number> {
const { args, stdout } = context;
stdout.write(cmdName + ': ' + args.join(','));
return ExitCode.SUCCESS;
}
```
and generated JavaScript bundle `js-test.js`:
```js
var Module = (function (exports) {
'use strict';
const ExitCode = {
SUCCESS: 0}; …
```
=> Build JavaScript commands for testing using rollup

src/base_shell.ts, src/base_shell_worker.ts, src/buffered_io.ts, src/defs_internal.ts, test/serve/index.ts, test/serve/input_setup.ts, test/tests/utils.ts
Change output writing to the main thread to use `postMessage` rather than `SharedArrayBuffer` in the `BufferedIO` class. This is the start of efforts to reduce the dependency on `SharedArrayBuffer`. Because we no longer have direct confirmation that writes have finished, it has been necessary to add some small delays to the test suite to for the messages to be handled and acted upon.
=> Output via postMessage rather than SharedArrayBuffer

src/builtin/options.ts, test/tests/options.test.ts
Add tests for built-in command `Options`. Although these use playwright they actually run locally via `node` rather than in the browser.
=> Add tests for built-in command Options

src/buffered_io/shared_array_buffer_worker_io.ts
A negative timeout passed to `poll` by a WebAssembly command is treated as an infinite timeout, see https://man7.org/linux/man-pages/man2/poll.2.html.
This is not currently used in any WebAssembly commands but it is in some that I have been experimenting with locally.
=> Negative timeout passed to poll() means infinite timeout

src/base_shell.ts, src/base_shell_worker.ts, src/defs.ts, src/defs_internal.ts, src/index.ts, src/shell_manager.ts, test/integration-tests/shell_manager.test.ts, test/serve/index.ts
Add a string `id` to `Shell`, which should be unique (in a particular browser tab). It can be specified via `IOptions` when the shell is created, and if not a `uuid` is used. IDs are stored in the new `ShellManager`, and will be used for routing of service worker requests to the correct Shell.
=> Shell id, and stored in static ShellManager

demo/serve/demo.ts, src/base_shell.ts, src/base_shell_worker.ts, src/defs.ts, src/defs_internal.ts, src/drive_fs.ts, src/shell_impl.ts, src/shell_manager.ts, test/integration-tests/shell_manager.test.ts, test/serve/shell_setup.ts, tsconfig.json
Rename input options `id` to `shellId` and `driveFsBaseUrl` to `baseUrl`.
=> Rename input options shellId and baseUrl

.github/workflows/deploy.yml, .gitignore, README.md
Now that we no longer need to serve with cross-origin headers we can now deploy on github pages. This PR will build and deploy the demo site on every push to `main`.
=> Deploy on github pages

src/buffered_io/service_worker_utils.ts, src/commands/command_module_loader.ts, src/commands/wasm_command_runner.ts, src/shell_impl.ts, src/utils.ts, test/integration-tests/command/external-command.test.ts, test/unit-tests/utils.test.ts
Previously we were creating URLs somewhat simplistically by combining `baseUrl` and `path` strings or using `URL`. This worked fine in simple situations such as the local demo and testing, but in more complicated situations this wasn't always correct as it could lead to, for example, an incorrect number of slashes. In the `terminal` extension we would use JupyterLab's `URLExt.join` but we don't want to add a dependency on JupyterLab here, so instead this PR adds a new function `joinURL` to use the correct number of slashes.
=> Join URLs correctly with a single slash between baseUrl and path

src/buffered_io/defs.ts, src/buffered_io/service_worker_main_io.ts, src/buffered_io/service_worker_worker_io.ts, test/integration-tests/shell.test.ts
This fixes a bug when using the ServiceWorker for `stdin` and a command such as `vim` which calls `poll` with a `timeout` to check if there is input available. If the call times out without any input then `stdin` should still be classified as readable so that the next `poll` call occurs. `vim` does this with a 4 second timeout, so I have added a slow (more than 4 second) test to verify the fix.
This also includes some streamlining of the `timeout` handling code.
The SharedArrayBuffer implementation is already working correctly.
=> Fix handling of timeout when vim uses service worker for stdin

demo/serve/demo.ts, src/base_shell.ts, src/base_shell_worker.ts, src/commands/command_registry.ts, src/defs.ts, src/defs_internal.ts, src/shell_impl.ts, test/integration-tests/command/external-command.test.ts, test/serve/shell_setup.ts
This changes the registration of `ExternalCommand`s to occur via `IOptions` in the `BaseShell` constructor rather than via `BaseShell.registerExternalCommand`. If we keep it as it is via the separate register function then we have to deal with it being called at any time, such as when a WebAssembly command is running. By setting them in the constructor we can ensure the registration is complete before the shell is `ready`.
This will make no difference to the JupyterLite terminal as external commands are registered with the one and only  `LiteTerminalAPIClient` and they are set on each `Shell` as it is created.
=> Register external xommands in Shell constructor only

demo/serve/demo.ts, src/base_shell.ts, src/callback_internal.ts, src/commands/external_command_runner.ts, src/context/external_context.ts, src/defs.ts, src/defs_internal.ts, src/external_environment.ts, src/index.ts, src/shell_impl.ts, test/integration-tests/command/external-command.test.ts, test/serve/external_command.ts, test/serve/shell_setup.ts
Improve `ExternalEnvironment` which are the environment variables passed to external commands, by supporting the deletion of environment variables and only copying back to the webworker environment those environment variables that have been deleted or changed, not all of them.
Fixes #179.
=> Improved `ExternalEnvironment`

src/base_shell.ts, src/environment.ts, src/shell_impl.ts, src/termios.ts
Use `termios` raw mode to get terminal background color when determining if dark mode or not. This disables the echo of input to output that can cause output of unnecessary newlines. Also supporting dark mode of `undefined` if the identification fails, this currently behaves as though it is using light mode but could be made distinct in the future.
=> Use termios raw mode to get terminal background color

src/shell_impl.ts
Increase theme change timeout from 10 ms to 100 ms. 10 ms is enough for the demo in this repo, but in the JupyterLite terminal it is possible for it to take up to 20 ms (on fast hardware) when changing the theme of all of JupyterLite. So be cautious here and increase the timeout to 100 ms.
Later we can consider if this needs to be configurable via `IShell.IOptions`.
=> Increase theme change timeout to 100 ms

src/commands/wasm_command_runner.ts, src/shell_impl.ts, src/termios.ts
Previously if multiple theme changes occurred during a long running command such as `vim`, more than one handler could run at the same time. This was seen in the `terminal`. Here avoiding this by using a new `enum` to track the status of theme changes and avoid two being handled at the same time.
Outputting debug timings to `console.debug`, and changed a few previous `console.log` calls to the same.
=> Avoid multiple concurrent theme change handlers

src/builtin/alias_command.ts, src/builtin/cd_command.ts, src/builtin/export_command.ts, src/builtin/option.ts, src/builtin/options.ts, test/unit-tests/options.test.ts
Add `TrailingPathsOption` for builtin and external commands, derived from `TrailingStringsOption`. Will be needed for tab-completion of such commands, which is not yet implemented.
=> Add TrailingPathsOption

README.md, src/builtin/cockle_config_command.ts, src/builtin/option.ts, src/builtin/options.ts, test/integration-tests/command/cockle-config-command.test.ts, test/integration-tests/command/external-command.test.ts, test/integration-tests/shell.test.ts, test/serve/shell_setup.ts, test/unit-tests/options.test.ts
This PR adds support for subcommands in built-in, javascript and external commands. These have the form
```bash
command subcommand [subcommand-options]
```
They can be nested so it is possible to have subcommands of subcommands.
To demonstrate, I have changed the `cockle-config` command to use subcommands, for example `cockle-config -s` is now `cockle-config stdin` and `cockle-config -p` is now `cockle-config package`.
This will make more sense when we have tab completion implemented using the various `Option` classes.
=> Support subcommand options

src/base_shell.ts, src/base_shell_worker.ts, src/buffered_io/main.ts, src/buffered_io/service_worker_main_io.ts, src/buffered_io/shared_array_buffer_main_io.ts, src/buffered_io/worker_io.ts, src/shell_impl.ts
Disable buffered IO before switching it using `cockle-config stdin <whatever>`. This is a bug fix as it was not explicitly disabled before this, although that did not cause any runtime problems. Also allow buffered IO `disable()` to be called even if it has not been enabled, in which case it is a no-op.
=> Disable buffered IO before switching it

src/shell_impl.ts, src/tools/prepare_wasm.ts, test/cockle-config-in.json, test/integration-tests/command/alias.test.ts, test/integration-tests/command/cockle-config-command.test.ts, test/integration-tests/command/env.test.ts
Support setting environment variables in `cockle-config-in.json`. Closes #117.
=> Support setting environment variables in cockle-config-in.json

src/io/external_output.ts
Change `IExternalOutput` to inherit from `IOutput` so that output in external commands can be used where a conventional `IOutput` is expected. An example is using `Table.write` in an external command, to write a formatted table.
=> Make `IExternalOutput` compatible with `IOutput`

src/builtin/alias_command.ts, src/builtin/cd_command.ts, src/builtin/cockle_config_command.ts, src/builtin/export_command.ts, src/builtin/history_command.ts, src/builtin/option.ts, src/builtin/options.ts, src/tab_complete.ts, src/tab_completer.ts, test/integration-tests/tab_completer.test.ts
This moves the handling of tab completion for built-in commands to the `Options` classes, so that there is a generic solution based on the command options rather than each command having to implement its own logic. Here is an example of tab-completing a `cockle-config package` subcommand with a particular package name:
https://github.com/user-attachments/assets/27178501-2ff0-484e-884c-3d5ab223abbe
It also includes tab completion of `-x` and `--whatever` options, and of directories (not files) for `cd`.
To use this, a builtin command should implement a `tabComplete` function like:
```ts
async tabComplete(context: ITabCompleteContext): Promise<ITabCompleteResult> {
return await new CockleConfigOptions().tabComplete(context);
}
```
Some `Option` classes accept callback functions to return …
=> Perform tab completion in `Options` classes

test/integration-tests/playwright.config.ts, test/package.json
Trying out listing all playwright tests that are run, even if they all pass. It works for me locally although the output is bit busy, let's see what it looks like in CI.
=> List all playwright tests, even if they all pass

demo/assets/index.html, demo/serve/demo.ts, demo/serve/index.ts, src/base_shell.ts, src/base_shell_worker.ts, src/defs.ts, src/defs_internal.ts, src/shell_impl.ts, test/integration-tests/shell.test.ts
Sometimes in JupyterLab/Lite if the theme is changed it is known whether the theme is light or dark mode. To support this, adding an optional boolean argument to `IShell.themeChange`. If the theme mode is known then the `Shell` assumes that is correct. If the theme is not known (argument is `undefined`) then it checks the background color by asking the terminal as before.
=> Pass optional dark/light mode boolean to `IShell.themeChange`

src/base_shell.ts, src/base_shell_worker.ts, src/defs.ts, src/defs_internal.ts, src/shell_impl.ts, test/integration-tests/command/external-command.test.ts, test/integration-tests/command/js-commands.test.ts, test/integration-tests/command/sed.test.ts, test/integration-tests/command/tee.test.ts, test/integration-tests/command/wasm-commands.test.ts, test/integration-tests/shell.test.ts
This PR exposes `IShell.exitCode` which returns the integer exit code of the last command run. This could conceivably be of use to someone with an `IShell`, and is of great benefit in the tests as we can now explicitly check the last exit code rather than running an `env | grep ?` which is what has been used until now.
Most of the tests have been modified to use the new function, just one remains testing `env | grep ?` as it is important that the env var is tested somewhere.
=> Expose IShell.exitCode() and use in exit code tests

demo/serve/external_command_tab.ts, src/argument.ts, src/arguments.ts, src/builtin/cockle_config_command.ts, src/builtin/help_command.ts, src/builtin/which_command.ts, test/serve/external_command_tab.ts, test/util-js/src/js-tab.ts
Make `PositionalArguments.possibles` async so that implementors of external commands can call async functions.
=> Make PositionalArguments.possibles async

src/argument.ts, src/arguments.ts, src/builtin/alias_command.ts, src/builtin/cockle_config_command.ts, src/layout/table.ts, test/integration-tests/command/help.test.ts
Up to now been showing only short name options such as `-v` in builtin command help. Here adding long name options too such as `--version`. 
Also switched to using `Table` for display of help information for both options and subcommands, as this aligns columns automatically.
=> Show both short and long name options for builtin command help

src/tab_completer.ts, test/integration-tests/command/external-command.test.ts, test/integration-tests/tab_completer.test.ts
Add support for tab completion of the last of multiple commands separated by semicolons on the same command line:
https://github.com/user-attachments/assets/cb28881b-8ba6-4d83-800c-9125ca6a99cd
=> Support tab completion of the last of multiple commands
