.github/workflows/prep-release.yml, package-lock.json
=> Update default version spec to `patch`

src/shell.ts, test/tests/shell.test.ts
This implements tab completion of directory and filenames, to accompany the existing tab completion of command and alias names.
=> Tab complete file and directory names

package-lock.json, package.json
Update to jupyterlab 7.2.5 and jupyterlite 0.4.1
=> Update to jupyterlab 7.2.5 and jupyterlite 0.4.1

README.md, demo/serve/demo.ts, package.json, src/command_registry.ts, src/commands/lua_command_runner.ts, test/tests/command/lua.test.ts
Add `lua` WASM command, it makes a good demo:
Running it as a script as shown above works fine, interactive running does not (due to buffering of stdin/out).
=> Add lua WASM command

src/ansi.ts, src/builtin/cockle_config_command.ts, src/command_registry.ts, src/commands/wasm_command_module.ts, src/commands/wasm_command_package.ts, src/commands/wasm_command_runner.ts, src/context.ts, src/shell_impl.ts, src/tools/prepare_wasm.ts, src/utils.ts
Show wasm package info in `cockle-config` command:
This will help when diagnosing problems to identify exactly which build of each package is being used.
=> Show wasm package info in cockle-config command

.github/workflows/test.yml
Run end-to-end tests on macos as well as ubuntu.
=> Run end-to-end tests on macos as well as ubuntu

test/tests/command/cp.test.ts, test/tests/command/mv.test.ts
Add new tests for `cp` and `mv` commands.
=> Add tests for cp and mv

test/serve/index.ts, test/serve/shell_setup.ts, test/tests/aliases.test.ts, test/tests/command/ls.test.ts, test/tests/command/stty.test.ts, test/tests/command/touch.test.ts, test/tests/history.test.ts, test/tests/io/file_input.test.ts, test/tests/shell.test.ts, test/tests/utils.ts
Some test function names are not camelCase for some reason, this PR fixes them.
=> Ensure function names are camelCase

package-lock.json, package.json, src/tools/prepare_wasm.ts
Check and recreate `cockle_wasm_env` if it does not contain all required packages.
=> Check and recreate cockle_wasm_env if it does not contain all required packages

src/commands/wasm_command_runner.ts
As part of the upgrade from emsdk 3.1.58 to 3.1.73 (issue #93) we need to handle the exit code from a wasm command being set via the `onExit` callback. Keeping the `quit` callback for the same for backward compatibility. In addition, check before closing `FS.streams` at the end of command as in future they may have been closed already.
=> Handle onExit callback from wasm to set exit code

src/commands/wasm_command_runner.ts, src/termios.ts
Log `termios` changes to the console to help when experimenting with new wasm commands.
=> Log termios changes to console

src/shell_impl.ts
Use `switch` statements instead of nested `if-else` statements for handling input. No functional change.
=> Use switch statements instead of nested if-else

src/commands/wasm_command_runner.ts, src/context.ts, src/file_system.ts, src/shell_impl.ts
Move `mountpoint` to `IFileSystem`, it doesn't need to be a direct property of `ShellImpl`.
=> Move mountpoint to IFileSystem

src/builtin/alias_command.ts, src/builtin/builtin_command.ts, src/builtin/cd_command.ts, src/builtin/clear_command.ts, src/builtin/cockle_config_command.ts, src/builtin/exit_command.ts, src/builtin/export_command.ts, src/builtin/history_command.ts, src/commands/command_runner.ts, src/commands/wasm_command_runner.ts, src/context.ts, src/index.ts, src/shell_impl.ts
Use interface `IContext` instead of class `Context`.
=> Use interface IContext instead of class Context

src/tools/prepare_wasm.ts
Print micromamba version used to deploy.
=> Print micromamba version used to deploy

test/tests/command/vim.test.ts
Add `vim` test using multi-char escape sequences (arrow keys)
=> Add vim test using multi-char escape sequences (arrow keys)

.github/workflows/check-release.yml, .github/workflows/prep-release.yml, .github/workflows/publish-release.yml, .github/workflows/test.yml
=> Remove micromamba pin in CI

CHANGELOG.md
Remove stale changelog entries for pre-releases.
=> Remove stale changelog entries for pre-releases

src/command_line.ts, src/shell_impl.ts, src/tab_completer.ts, test/integration-tests/command/lua.test.ts
Move tab completion to separate class, in preparation for extending it.
=> Move tab completion to separate class

src/tab_completer.ts, test/integration-tests/shell.test.ts
Make tab completion more modular, making it easier to extend.
=> Make tab completion more modular
